//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("FormOTPM", Namespace="", IsNullable=false)]
public partial class FormOTPMType : INFormType {
    
    private OTPReturnSection returnSectionAField;
    
    private OTPScheduleSection2[] returnSectionBField;
    
    /// <remarks/>
    public OTPReturnSection ReturnSectionA {
        get {
            return this.returnSectionAField;
        }
        set {
            this.returnSectionAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("OTPScheduleRepeatSection", IsNullable=false)]
    public OTPScheduleSection2[] ReturnSectionB {
        get {
            return this.returnSectionBField;
        }
        set {
            this.returnSectionBField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class OTPReturnSection {
    
    private ReturnFilingTypeType returnFilingTypeField;
    
    private decimal purchasesField;
    
    private decimal purchases2Field;
    
    private decimal tobaccoShippedOutOfStateField;
    
    private decimal tobaccoShippedOutOfState2Field;
    
    private decimal tobaccoReturnedField;
    
    private decimal tobaccoReturned2Field;
    
    private decimal salesToFedGovtField;
    
    private decimal salesToFedGovt2Field;
    
    private decimal taxPaidPurchasesField;
    
    private decimal taxPaidPurchases2Field;
    
    private decimal untaxedSalesToINDistribField;
    
    private decimal untaxedSalesToINDistrib2Field;
    
    private decimal totalDeductionsField;
    
    private decimal totalDeductions2Field;
    
    private decimal deductionAddBackField;
    
    private decimal deductionAddBack2Field;
    
    private decimal taxableTobaccoAfterDeductionsField;
    
    private decimal taxableTobaccoAfterDeductions2Field;
    
    private decimal taxOnTobaccoProdsField;
    
    private decimal taxOnTobaccoProds2Field;
    
    private decimal totalTaxOnTobaccoProductsField;
    
    private decimal collectionAllowanceField;
    
    private decimal taxDueField;
    
    private decimal penaltyField;
    
    private decimal interestField;
    
    private decimal totalWithPandIField;
    
    private decimal intrastateSalesField;
    
    private decimal intrastateSales2Field;
    
    /// <remarks/>
    public ReturnFilingTypeType ReturnFilingType {
        get {
            return this.returnFilingTypeField;
        }
        set {
            this.returnFilingTypeField = value;
        }
    }
    
    /// <remarks/>
    public decimal Purchases {
        get {
            return this.purchasesField;
        }
        set {
            this.purchasesField = value;
        }
    }
    
    /// <remarks/>
    public decimal Purchases2 {
        get {
            return this.purchases2Field;
        }
        set {
            this.purchases2Field = value;
        }
    }
    
    /// <remarks/>
    public decimal TobaccoShippedOutOfState {
        get {
            return this.tobaccoShippedOutOfStateField;
        }
        set {
            this.tobaccoShippedOutOfStateField = value;
        }
    }
    
    /// <remarks/>
    public decimal TobaccoShippedOutOfState2 {
        get {
            return this.tobaccoShippedOutOfState2Field;
        }
        set {
            this.tobaccoShippedOutOfState2Field = value;
        }
    }
    
    /// <remarks/>
    public decimal TobaccoReturned {
        get {
            return this.tobaccoReturnedField;
        }
        set {
            this.tobaccoReturnedField = value;
        }
    }
    
    /// <remarks/>
    public decimal TobaccoReturned2 {
        get {
            return this.tobaccoReturned2Field;
        }
        set {
            this.tobaccoReturned2Field = value;
        }
    }
    
    /// <remarks/>
    public decimal SalesToFedGovt {
        get {
            return this.salesToFedGovtField;
        }
        set {
            this.salesToFedGovtField = value;
        }
    }
    
    /// <remarks/>
    public decimal SalesToFedGovt2 {
        get {
            return this.salesToFedGovt2Field;
        }
        set {
            this.salesToFedGovt2Field = value;
        }
    }
    
    /// <remarks/>
    public decimal TaxPaidPurchases {
        get {
            return this.taxPaidPurchasesField;
        }
        set {
            this.taxPaidPurchasesField = value;
        }
    }
    
    /// <remarks/>
    public decimal TaxPaidPurchases2 {
        get {
            return this.taxPaidPurchases2Field;
        }
        set {
            this.taxPaidPurchases2Field = value;
        }
    }
    
    /// <remarks/>
    public decimal UntaxedSalesToINDistrib {
        get {
            return this.untaxedSalesToINDistribField;
        }
        set {
            this.untaxedSalesToINDistribField = value;
        }
    }
    
    /// <remarks/>
    public decimal UntaxedSalesToINDistrib2 {
        get {
            return this.untaxedSalesToINDistrib2Field;
        }
        set {
            this.untaxedSalesToINDistrib2Field = value;
        }
    }
    
    /// <remarks/>
    public decimal TotalDeductions {
        get {
            return this.totalDeductionsField;
        }
        set {
            this.totalDeductionsField = value;
        }
    }
    
    /// <remarks/>
    public decimal TotalDeductions2 {
        get {
            return this.totalDeductions2Field;
        }
        set {
            this.totalDeductions2Field = value;
        }
    }
    
    /// <remarks/>
    public decimal DeductionAddBack {
        get {
            return this.deductionAddBackField;
        }
        set {
            this.deductionAddBackField = value;
        }
    }
    
    /// <remarks/>
    public decimal DeductionAddBack2 {
        get {
            return this.deductionAddBack2Field;
        }
        set {
            this.deductionAddBack2Field = value;
        }
    }
    
    /// <remarks/>
    public decimal TaxableTobaccoAfterDeductions {
        get {
            return this.taxableTobaccoAfterDeductionsField;
        }
        set {
            this.taxableTobaccoAfterDeductionsField = value;
        }
    }
    
    /// <remarks/>
    public decimal TaxableTobaccoAfterDeductions2 {
        get {
            return this.taxableTobaccoAfterDeductions2Field;
        }
        set {
            this.taxableTobaccoAfterDeductions2Field = value;
        }
    }
    
    /// <remarks/>
    public decimal TaxOnTobaccoProds {
        get {
            return this.taxOnTobaccoProdsField;
        }
        set {
            this.taxOnTobaccoProdsField = value;
        }
    }
    
    /// <remarks/>
    public decimal TaxOnTobaccoProds2 {
        get {
            return this.taxOnTobaccoProds2Field;
        }
        set {
            this.taxOnTobaccoProds2Field = value;
        }
    }
    
    /// <remarks/>
    public decimal TotalTaxOnTobaccoProducts {
        get {
            return this.totalTaxOnTobaccoProductsField;
        }
        set {
            this.totalTaxOnTobaccoProductsField = value;
        }
    }
    
    /// <remarks/>
    public decimal CollectionAllowance {
        get {
            return this.collectionAllowanceField;
        }
        set {
            this.collectionAllowanceField = value;
        }
    }
    
    /// <remarks/>
    public decimal TaxDue {
        get {
            return this.taxDueField;
        }
        set {
            this.taxDueField = value;
        }
    }
    
    /// <remarks/>
    public decimal Penalty {
        get {
            return this.penaltyField;
        }
        set {
            this.penaltyField = value;
        }
    }
    
    /// <remarks/>
    public decimal Interest {
        get {
            return this.interestField;
        }
        set {
            this.interestField = value;
        }
    }
    
    /// <remarks/>
    public decimal TotalWithPandI {
        get {
            return this.totalWithPandIField;
        }
        set {
            this.totalWithPandIField = value;
        }
    }
    
    /// <remarks/>
    public decimal IntrastateSales {
        get {
            return this.intrastateSalesField;
        }
        set {
            this.intrastateSalesField = value;
        }
    }
    
    /// <remarks/>
    public decimal IntrastateSales2 {
        get {
            return this.intrastateSales2Field;
        }
        set {
            this.intrastateSales2Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
public enum ReturnFilingTypeType {
    
    /// <remarks/>
    O,
    
    /// <remarks/>
    A,
    
    /// <remarks/>
    ONA,
    
    /// <remarks/>
    ANA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class OTPScheduleSection2 {
    
    private OTPScheduleSection2TransactionType transactionTypeField;
    
    private DocumentTypeType documentTypeField;
    
    private System.DateTime documentDateField;
    
    private string documentNumberField;
    
    private string companyNameField;
    
    private string federalIDField;
    
    private string licenseNumberField;
    
    private string addressField;
    
    private string cityField;
    
    private StateType stateField;
    
    private string zipCodeField;
    
    private decimal wholesalePriceField;
    
    private decimal ouncesField;
    
    /// <remarks/>
    public OTPScheduleSection2TransactionType TransactionType {
        get {
            return this.transactionTypeField;
        }
        set {
            this.transactionTypeField = value;
        }
    }
    
    /// <remarks/>
    public DocumentTypeType DocumentType {
        get {
            return this.documentTypeField;
        }
        set {
            this.documentTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DocumentDate {
        get {
            return this.documentDateField;
        }
        set {
            this.documentDateField = value;
        }
    }
    
    /// <remarks/>
    public string DocumentNumber {
        get {
            return this.documentNumberField;
        }
        set {
            this.documentNumberField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyName {
        get {
            return this.companyNameField;
        }
        set {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    public string FederalID {
        get {
            return this.federalIDField;
        }
        set {
            this.federalIDField = value;
        }
    }
    
    /// <remarks/>
    public string LicenseNumber {
        get {
            return this.licenseNumberField;
        }
        set {
            this.licenseNumberField = value;
        }
    }
    
    /// <remarks/>
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public StateType State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public string ZipCode {
        get {
            return this.zipCodeField;
        }
        set {
            this.zipCodeField = value;
        }
    }
    
    /// <remarks/>
    public decimal WholesalePrice {
        get {
            return this.wholesalePriceField;
        }
        set {
            this.wholesalePriceField = value;
        }
    }
    
    /// <remarks/>
    public decimal Ounces {
        get {
            return this.ouncesField;
        }
        set {
            this.ouncesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum OTPScheduleSection2TransactionType {
    
    /// <remarks/>
    A,
    
    /// <remarks/>
    B,
    
    /// <remarks/>
    C,
    
    /// <remarks/>
    D,
    
    /// <remarks/>
    E,
    
    /// <remarks/>
    F,
    
    /// <remarks/>
    G,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
public enum DocumentTypeType {
    
    /// <remarks/>
    C,
    
    /// <remarks/>
    I,
    
    /// <remarks/>
    O,
    
    /// <remarks/>
    PO,
    
    /// <remarks/>
    CM,
    
    /// <remarks/>
    A,
    
    /// <remarks/>
    RG,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
public enum StateType {
    
    /// <remarks/>
    AL,
    
    /// <remarks/>
    AK,
    
    /// <remarks/>
    AS,
    
    /// <remarks/>
    AZ,
    
    /// <remarks/>
    AR,
    
    /// <remarks/>
    CA,
    
    /// <remarks/>
    CO,
    
    /// <remarks/>
    MP,
    
    /// <remarks/>
    CT,
    
    /// <remarks/>
    DE,
    
    /// <remarks/>
    DC,
    
    /// <remarks/>
    FM,
    
    /// <remarks/>
    FL,
    
    /// <remarks/>
    GA,
    
    /// <remarks/>
    GU,
    
    /// <remarks/>
    HI,
    
    /// <remarks/>
    ID,
    
    /// <remarks/>
    IL,
    
    /// <remarks/>
    IN,
    
    /// <remarks/>
    IA,
    
    /// <remarks/>
    KS,
    
    /// <remarks/>
    KY,
    
    /// <remarks/>
    LA,
    
    /// <remarks/>
    ME,
    
    /// <remarks/>
    MH,
    
    /// <remarks/>
    MD,
    
    /// <remarks/>
    MA,
    
    /// <remarks/>
    MI,
    
    /// <remarks/>
    MN,
    
    /// <remarks/>
    MS,
    
    /// <remarks/>
    MO,
    
    /// <remarks/>
    MT,
    
    /// <remarks/>
    NE,
    
    /// <remarks/>
    NV,
    
    /// <remarks/>
    NH,
    
    /// <remarks/>
    NJ,
    
    /// <remarks/>
    NM,
    
    /// <remarks/>
    NY,
    
    /// <remarks/>
    NC,
    
    /// <remarks/>
    ND,
    
    /// <remarks/>
    OH,
    
    /// <remarks/>
    OK,
    
    /// <remarks/>
    OR,
    
    /// <remarks/>
    PW,
    
    /// <remarks/>
    PA,
    
    /// <remarks/>
    PR,
    
    /// <remarks/>
    RI,
    
    /// <remarks/>
    SC,
    
    /// <remarks/>
    SD,
    
    /// <remarks/>
    TN,
    
    /// <remarks/>
    TX,
    
    /// <remarks/>
    VI,
    
    /// <remarks/>
    UT,
    
    /// <remarks/>
    VT,
    
    /// <remarks/>
    VA,
    
    /// <remarks/>
    WA,
    
    /// <remarks/>
    WV,
    
    /// <remarks/>
    WI,
    
    /// <remarks/>
    WY,
    
    /// <remarks/>
    AA,
    
    /// <remarks/>
    AE,
    
    /// <remarks/>
    AP,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FormOTPMType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public abstract partial class INFormType {
}
